### ISSUE TITLE
Add resources on building good forms

### ISSUE THREAD

**Issue by aviv** [dobtco/knowledge_base#144]
We want to position ourselves as "form experts," so let's think about how we can set down some guidelines on how to use Screendoor to build great forms.

cf. #143

**Comment by ajb** [comment]
I would consider blogging about this, and then linking to the blog from a "resources" page in the kb.

**Comment by jrubenoff** [comment]
It can also be nice to centralize it, just from a branding perspective:

http://templates.mailchimp.com/

Or even nicer:

http://mailchimp.com/resources/

**Comment by ajb** [comment]
@aviv: let's work on this now.

**Comment by aviv** [comment]
https://github.com/dobtco/knowledge_base/blob/resources/contents/articles/additional_resources/content/good_forms.md

**Comment by jrubenoff** [comment]
Cool! I like the idea of using live forms. I rearranged the wording a bit, and made "Succinct" more succinct. :smile: 

It seems like you're leaning towards making this a bunch of little style guidelines, rather than some major overarching principles. Here are two sites which do this well:

http://voiceandtone.com
https://www.tumblr.com/logo

**Comment by aviv** [comment]
Thanks, +1 on the edits. Not sure about the style guidelines vs. major overarching principles question; hopefully there'll be room for both. Might be that it's just harder to approach the latter without a concrete example.

**Comment by aviv** [comment]
Closing for PR
